WITH base AS (
    SELECT
        REPLACE(REPLACE(UPPER(GENRES), '[', ''), ']', '') AS GENRES,
        TYPE
    FROM {{ ref('SHOW_DETAILS_DIM') }}
    WHERE GENRES IS NOT NULL
      AND TYPE IN ('MOVIE', 'SHOW')
),
agg AS (
    SELECT
        GENRES,
        SUM(CASE WHEN TYPE = 'MOVIE' THEN 1 ELSE 0 END) AS TOTAL_MOVIES,
        SUM(CASE WHEN TYPE = 'SHOW' THEN 1 ELSE 0 END) AS TOTAL_SHOWS
    FROM base
    GROUP BY 1
)
 
SELECT
    GENRES,
    ROUND(100 * TOTAL_MOVIES / NULLIF(TOTAL_MOVIES + TOTAL_SHOWS, 0), 2) AS MOVIE_PERCENTAGE_SHARE,
    ROUND(100 * TOTAL_SHOWS / NULLIF(TOTAL_MOVIES + TOTAL_SHOWS, 0), 2) AS SERIES_PERCENTAGE_SHARE
FROM agg